[versions]
agp = "8.13.2"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
androidx-activity = "1.12.1"
androidx-lifecycle = "2.10.0-alpha07"
appcompat = "1.7.1"
composeMultiplatform = "1.9.3"
fluentui-icons = "1.0.1"
kotlin = "2.3.0"
kotzilla = "1.4.2-RC1"
cmpNavigation3 = "1.0.0-alpha06"
adaptive = "1.2.0"
ktor="3.3.3"
material = "1.13.0"
media="1.9.0"
corotine="1.10.2"
ksp = "2.2.21-RC-2.0.4"
koin-core = "4.1.1"
koin-annotations = "2.3.1"
media3Ui = "1.9.0"
core-splashscreen = "1.2.0"
multiplatform-settings = "1.3.0"
androidx-datastore = "1.1.1"

[libraries]
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
fluentui-system-icons = { module = "io.github.niyajali:fluentui-system-icons", version.ref = "fluentui-icons" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotzilla-sdk-compose = { group = "io.kotzilla", name = "kotzilla-sdk-compose", version.ref = "kotzilla" }

koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin-core" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin-core" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin-core" }
koin-compose-viewmodel-navigation = { module = "io.insert-koin:koin-compose-viewmodel-navigation", version.ref = "koin-core" }
koin-ksp-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koin-annotations" }

jetbrains-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "cmpNavigation3" }
jetbrains-lifecycle-viewmodel-nav3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
jetbrains-lifecycle-viewmodel = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel", version.ref = "androidx-lifecycle"}



material = { module = "com.google.android.material:material", version.ref = "material" }
material3-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }

ktor-client={module="io.ktor:ktor-client-core",version.ref="ktor"}
ktor-client-auth={module="io.ktor:ktor-client-auth",version.ref="ktor"}
ktor-client-call-logging={module="io.ktor:ktor-client-logging",version.ref="ktor"}
ktor-content-negotiation={module="io.ktor:ktor-client-content-negotiation",version.ref="ktor"}
ktor-serialization={module="io.ktor:ktor-serialization-kotlinx-json",version.ref="ktor"}
ktor-android-okhttp={module="io.ktor:ktor-client-okhttp",version.ref="ktor"}
ktor-ios-darwin={module="io.ktor:ktor-client-darwin",version.ref="ktor"}

android-video={module="androidx.media3:media3-exoplayer",version.ref="media"}

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
kotlin-corotines={module="org.jetbrains.kotlinx:kotlinx-coroutines-core",version.ref="corotine"}
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "media3Ui" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "core-splashscreen" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatform-settings" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotzilla = { id = "io.kotzilla.kotzilla-plugin", version.ref = "kotzilla" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]
ktor-client=['ktor-client','ktor-client-auth','ktor-content-negotiation','ktor-client-call-logging']